name: SBOM 

on:

  workflow_dispatch:
  pull_request:
    branches:
      - "*"

jobs:
  sbom:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install xsltproc
        run: sudo apt-get update && sudo apt-get install -y xsltproc

      - name: Generate SBOM (CycloneDX)
        run: ./gradlew cyclonedxBom

      - name: Convert SBOM to HTML
        run: xsltproc sbom/cyclonedx-xml-to-html.xslt build/reports/bom.xml > sbom.html

      - name: Upload SBOM as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.html
